import { useState } from "react";
import { Link } from "react-router-dom";
import CartSummary from "../components/store/CartSummary";
import WhatsAppOrderButton from "../components/store/WhatsAppOrderButton";
import { useCart } from "../context/CartContext";

const initialCustomer = { name: "", phone: "", address: "", note: "" };

export default function Checkout() {
  const { items, itemCount, total, clearCart } = useCart();
  const [customer, setCustomer] = useState(initialCustomer);
  const [error, setError] = useState("");
  const [confirmation, setConfirmation] = useState(false);
  const [whatsAppError, setWhatsAppError] = useState("");

  const updateField = (event) => setCustomer({ ...customer, [event.target.name]: event.target.value });
  const handleInitiated = (launchError) => { if (launchError) { setWhatsAppError("WhatsApp could not be opened. Please check your browser pop-up settings and try again."); return; } clearCart(); setConfirmation(true); };
  const handleSubmit = (event) => { event.preventDefault(); setError(""); setWhatsAppError(""); if (!customer.name.trim() || !customer.phone.trim() || !customer.address.trim()) { setError("Please enter your name, WhatsApp number and contact information."); return; } setError("ready"); };

  if (confirmation) return <main className="min-h-[70vh] bg-white px-6 pb-24 pt-40 text-center"><div className="mx-auto max-w-xl"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-green-100 text-3xl text-green-700">✓</div><p className="mt-7 text-sm font-bold uppercase tracking-[0.2em] text-green-700">WhatsApp opened</p><h1 className="mt-3 text-4xl font-black">Your order details are ready.</h1><p className="mt-5 leading-8 text-slate-600">We opened WhatsApp with your order message. Sending it there starts the conversation with Harry Innovative Technologies; payment has not been completed.</p><Link to="/store" className="mt-8 inline-flex rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Return to store</Link></div></main>;
  if (items.length === 0) return <main className="min-h-[70vh] bg-white px-6 pb-24 pt-40 text-center"><h1 className="text-4xl font-black">Nothing to check out yet</h1><p className="mt-4 text-slate-600">Add a product or installation service to your cart before continuing.</p><Link to="/store" className="mt-8 inline-flex rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Browse the store</Link></main>;

  return <main className="bg-slate-50 pb-24 pt-32 text-slate-950"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.2em] text-blue-600">Store checkout</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Tell us where to start.</h1><div className="mt-12 grid gap-8 lg:grid-cols-[1fr_360px]"><form onSubmit={handleSubmit} className="rounded-2xl bg-white p-6 shadow-sm sm:p-8"><div className="grid gap-6 sm:grid-cols-2"><label className="text-sm font-bold">Full name<input name="name" value={customer.name} onChange={updateField} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-blue-500" placeholder="John Doe" /></label><label className="text-sm font-bold">WhatsApp phone number<input name="phone" value={customer.phone} onChange={updateField} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-blue-500" placeholder="08012345678" /></label></div><label className="mt-6 block text-sm font-bold">Delivery or contact information<textarea name="address" value={customer.address} onChange={updateField} rows="3" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-blue-500" placeholder="Business address, email or preferred contact details" /></label><label className="mt-6 block text-sm font-bold">Optional note<textarea name="note" value={customer.note} onChange={updateField} rows="3" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-blue-500" placeholder="Anything you would like us to know?" /></label>{error && error !== "ready" && <p className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</p>}{whatsAppError && <p className="mt-5 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{whatsAppError}</p>}<div className="mt-7">{error === "ready" ? <WhatsAppOrderButton customer={customer} items={items} total={total} onInitiated={handleInitiated} /> : <button type="submit" className="w-full rounded-xl bg-slate-950 px-5 py-4 text-sm font-black text-white transition hover:bg-blue-700">Review order details</button>}</div><p className="mt-4 text-center text-xs leading-5 text-slate-500">No card, banking or payment credentials are collected. Product availability, installation requirements and final pricing will be confirmed manually on WhatsApp.</p></form><CartSummary itemCount={itemCount} total={total} checkout={false} /></div></div></main>;
}
